#!/usr/bin/env bash
#MISE dir="{{cwd}}"
#MISE description="Use gh auth token"

mise config set env.GITHUB_TOKEN.value '{{ exec(command='\''gh auth token'\'') }}'
mise config set env.GITHUB_TOKEN.redact true
