#!/usr/bin/env bash
#MISE dir="{{cwd}}"
#MISE depends=["preset:pre-commit"]

mise tasks add pre-commit:cargo-fmt -- cargo fmt --check

if command -v cargo-nextest &>/dev/null; then
  mise config set tasks.test.run 'cargo nextest run --no-fail-fast ${usage_filters}'
else
  mise config set tasks.test.run 'cargo test --no-fail-fast -- ${usage_filters}'
fi
mise config set tasks.test.usage 'arg "[filters]" var=#true'
