#!/usr/bin/env bash
#MISE dir="{{cwd}}"
#MISE depends=["preset:pre-commit"]

mise tasks add pre-commit:cargo-fmt -- cargo fmt --check
if command -v cargo-nextest &>/dev/null; then
  mise tasks add test -- cargo nextest run --no-fail-fast --nocapture '{{vars.cargo_test_args}}'
else
  mise tasks add test -- cargo test --no-fail-fast -- --nocapture '{{vars.cargo_test_args}}'
fi
