#!/usr/bin/env bash
#MISE dir="~"
#MISE description="Update all apps"

if command -v apt &>/dev/null; then
    sudo apt update && sudo apt upgrade
fi

if command -v brew &>/dev/null; then
    brew update && brew upgrade
fi

if command -v paru &>/dev/null; then
    paru -Syu
fi

if command -v uv &>/dev/null; then
    mise run g:app:uv:up
fi

if command -v pnpm &>/dev/null; then
    mise run g:app:pnpm:up
fi