#!/usr/bin/env zsh
export LANG=en_US.UTF-8
export LC_CTYPE=$LANG
export LC_ALL=$LANG
export RUBYLIB=$HOME/.rubylib
export FCEDIT="vim"
export EDITOR="emacs-dwim"
export VISUAL="$EDITOR"
export ALTERNATE_EDITOR="vim"
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;32'
export rvm_path="$HOME/.rvm"

export PATH="$HOME/bin:$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
