#!/bin/zsh

if [[  "$-" != *i* ]]; then return 0; fi

if [ -z "$OS_TYPE" ]; then
  export OS_TYPE=$(uname -s)
fi

zstyle :omz:plugins:ssh-agent agent-forwarding on

ZSH="$HOME/.zsh"
OZSH="$HOME/.oh-my-zsh"

for f in $ZSH/*.zsh; do
  [ -f "$f" ] && source "$f"
done
if [ "$OS_TYPE" != "Darwin" ]; then
  [ -f "$HOME/.xenv" ] && source "$HOME/.xenv"
fi

JIRA_RAPID_BOARD=yes
for p in jira django; do
  [ -f "$OZSH/plugins/${p}/${p}.plugin.zsh" ] && source "$OZSH/plugins/${p}/${p}.plugin.zsh"
done

##################################################
# Command Edit
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# setopt hist_ignore_dups
# share command history data
setopt share_history

setopt hist_verify
setopt inc_append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_space

setopt share_history
setopt append_history

setopt auto_cd
setopt auto_name_dirs
setopt auto_pushd
setopt pushd_ignore_dups
setopt cdablevars
# setopt pushd_ignore_dups

##################################################
# Misc Options

# jobs
setopt long_list_jobs
unsetopt hup
unsetopt bg_nice
setopt check_jobs
setopt notify

# Expansion and Globbing
setopt extended_glob
setopt null_glob

# Input Output
setopt clobber
setopt interactivecomments
setopt multios

# Correction
setopt no_correct

##################################################
# Other

# remeber parent TTY
export TMUX_TTY="$TTY"
