#!/usr/bin/env zsh
export LANG=en_US.UTF-8
export LC_CTYPE=$LANG
export LC_ALL=$LANG
export RUBYLIB=$HOME/.rubylib
export FCEDIT="emacs-dwim -t"
export VISUAL="emacs-dwim -t"
export EDITOR="emacs-dwim"
export ALTERNATE_EDITOR="vim"
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;32'
export rvm_path="$HOME/.rvm"
export EMACS=emacs
export EMACSCLIENT=emacsclient

# ruby perf
export RUBY_HEAP_MIN_SLOTS=1000000
export RUBY_HEAP_SLOTS_INCREMENT=1000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=1000000000
export RUBY_HEAP_FREE_MIN=500000

export PATH="$HOME/bin:$HOME/.rbenv/shims:$HOME/.rbenv/bin:$HOME/.cabal/bin:$PATH"
