#!/bin/sh
set -e

DIR="$(git config --get core.hooksPath 2>/dev/null || echo .git/hooks)"

if [ -f tags ]; then
  "$DIR/ctags" >/dev/null 2>&1 &
fi

if command -v git-lfs >/dev/null 2>&1; then
  if [ "$(git config --get lfs.enabled >/dev/null 2>/dev/null || true)" = true ]; then
    git lfs post-merge "$@"
  fi
fi
