#!/bin/sh
set -e

DIR="$(git config --get core.hooksPath 2>/dev/null || echo .git/hooks)"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color
PREFIX="${GREEN}[PRECOMMIT]${NC}"
FAILURE="${RED}FAILED${NC}"
WARNING="${RED}[WARNING]${NC}"
SKIPPED="${YELLOW}SKIPPED${NC}"
SUCCESS="${GREEN}ok${NC}"
FAILED=0

if git rev-parse --verify HEAD >/dev/null 2>/dev/null; then
  AGAINST_SHA=HEAD
else
  AGAINST_SHA=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

check_git() {
  printf "${PREFIX} Checking user.email is set ... "
  if [ -n "$(git config user.email)" ]; then
    printf "${SUCCESS}\n"
  else
    printf "${FAILURE}\n"
    return 1
  fi
}

check_whitespace() {
  printf "${PREFIX} Checking for bad whitespace ... "
  if git diff-index --check --cached $AGAINST_SHA >/dev/null 2>/dev/null; then
    printf "${SUCCESS}\n"
  else
    git diff-index --check --cached $AGAINST_SHA -- || true
    printf "${FAILURE}\n"
    return 1
  fi
}

run_mise_task() {
  if mise tasks info pre-commit --silent >/dev/null 2>/dev/null; then
    printf "${PREFIX} Running mise pre-commit:\n"
    mise run pre-commit
  fi
}

check_git
check_whitespace
run_mise_task
