#!/usr/bin/env bash

gh_token() {
  local GH_HOSTS_YML="${XDG_CONFIG_HOME:-"$HOME/.config"}/gh/hosts.yml"
  if [ -f "$GH_HOSTS_YML" ]; then
    GITHUB_TOKEN="$(grep 'oauth_token: ' "$GH_HOSTS_YML" | awk '{print $2}')"
    export GITHUB_TOKEN
  fi
}
