import { expect, test } from "bun:test";
import { mkdir, mkdtemp, readlink, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const script = fileURLToPath(new URL("../src/niri-scripts/waybar-optional.js", import.meta.url));

async function setupHome() {
  const home = await mkdtemp(join(tmpdir(), "waybar-optional "));
  const optional = join(home, ".config", "waybar", "optional");
  await mkdir(optional, { recursive: true });
  await writeFile(join(optional, "beta.jsonc"), '{"custom/beta": {}}\n');
  await writeFile(join(optional, "alpha.jsonc"), '{"custom/alpha": {}}\n');
  await writeFile(join(optional, "notes.txt"), "ignored");
  // Empty PATH keeps `killall -SIGUSR2 waybar` from touching a live waybar
  const bin = join(home, "bin");
  await mkdir(bin);
  const env = { ...process.env, HOME: home, USERPROFILE: home, PATH: bin };
  return { home, modules: join(home, ".config", "waybar", "modules"), optional, env };
}

async function run(env, ...args) {
  const child = Bun.spawn([process.execPath, script, ...args], {
    env,
    stdin: "ignore",
    stdout: "pipe",
    stderr: "pipe",
  });
  const [code, stdout, stderr] = await Promise.all([
    child.exited,
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
  ]);
  return { code, stdout, stderr };
}

test.skipIf(process.platform === "win32")(
  "discovers widgets from optional/, toggles them as symlinks in modules/",
  async () => {
    const { home, modules, optional, env } = await setupHome();
    try {
      expect(await run(env, "status")).toMatchObject({
        code: 0,
        stdout: "alpha: off\nbeta: off\n",
      });

      expect(await run(env, "on", "alpha")).toMatchObject({ code: 0, stdout: "alpha: on\n" });
      expect(await readlink(join(modules, "alpha.jsonc"))).toBe(join(optional, "alpha.jsonc"));
      expect(await run(env, "status")).toMatchObject({
        code: 0,
        stdout: "alpha: on\nbeta: off\n",
      });

      expect(await run(env, "toggle", "alpha")).toMatchObject({ code: 0, stdout: "alpha: off\n" });
      expect(await Bun.file(join(modules, "alpha.jsonc")).exists()).toBe(false);

      expect(await run(env, "toggle", "beta")).toMatchObject({ code: 0, stdout: "beta: on\n" });
      expect(await run(env, "off", "beta")).toMatchObject({ code: 0, stdout: "beta: off\n" });
      expect(await Bun.file(join(modules, "beta.jsonc")).exists()).toBe(false);
    } finally {
      await rm(home, { recursive: true, force: true });
    }
  },
);

test.skipIf(process.platform === "win32")(
  "on replaces a stale generated fragment with the symlink",
  async () => {
    const { home, modules, env } = await setupHome();
    try {
      await mkdir(modules, { recursive: true });
      await writeFile(join(modules, "alpha.jsonc"), "// generated by an older version\n{}\n");
      expect(await run(env, "on", "alpha")).toMatchObject({ code: 0, stdout: "alpha: on\n" });
      expect(await readlink(join(modules, "alpha.jsonc"))).toBe(
        join(home, ".config", "waybar", "optional", "alpha.jsonc"),
      );
    } finally {
      await rm(home, { recursive: true, force: true });
    }
  },
);

test.skipIf(process.platform === "win32")("unknown widgets and missing directories fail with usage", async () => {
  const { home, env } = await setupHome();
  try {
    const unknown = await run(env, "on", "nope");
    expect(unknown.code).toBe(1);
    expect(unknown.stderr).toContain("Usage: waybar-optional");
    expect(unknown.stderr).toContain("Widgets: alpha, beta");

    await rm(join(home, ".config", "waybar", "optional"), { recursive: true, force: true });
    expect(await run(env, "status")).toMatchObject({ code: 0, stdout: "" });
    const noWidgets = await run(env, "toggle", "alpha");
    expect(noWidgets.code).toBe(1);
    expect(noWidgets.stderr).toContain("Widgets: \n");
  } finally {
    await rm(home, { recursive: true, force: true });
  }
});
