local DENYLIST = {
  autoEqnLabels = true,
  autoSectionLabels = true,
  ccsDelim = true,
  ccsLabelSep = true,
  ccsTemplate = true,
  chapDelim = true,
  chapters = true,
  chaptersDepth = true,
  codeBlockCaptions = true,
  cref = true,
  crossrefYaml = true,
  eqLabels = true,
  eqnBlockInlineMath = true,
  eqnBlockTemplate = true,
  eqnIndexTemplate = true,
  eqnInlineTemplate = true,
  eqnPrefix = true,
  eqnPrefixTemplate = true,
  equationNumberTeX = true,
  figLabels = true,
  figPrefix = true,
  figPrefixTemplate = true,
  figureTemplate = true,
  figureTitle = true,
  lastDelim = true,
  linkReferences = true,
  listings = true,
  listingTemplate = true,
  listingTitle = true,
  listItemTitleDelim = true,
  lof = true,
  lofItemTemplate = true,
  lofTitle = true,
  lol = true,
  lolItemTemplate = true,
  lolTitle = true,
  lotItemTemplate = true,
  lotTitle = true,
  lstLabels = true,
  lstPrefix = true,
  lstPrefixTemplate = true,
  nameInLink = true,
  numberSections = true,
  pairDelim = true,
  rangeDelim = true,
  refDelim = true,
  refIndexTemplate = true,
  secHeaderDelim = true,
  secHeaderTemplate = true,
  secLabels = true,
  secPrefix = true,
  secPrefixTemplate = true,
  sectionsDepth = true,
  subfigGrid = true,
  subfigLabels = true,
  subfigureChildTemplate = true,
  subfigureRefIndexTemplate = true,
  subfigureTemplate = true,
  tableEqns = true,
  tableTemplate = true,
  tableTitle = true,
  tblLabels = true,
  tblPrefix = true,
  tblPrefixTemplate = true,
  titleDelim = true,
}

function Meta(meta)
  for k in pairs(meta) do
    if DENYLIST[k] ~= nil then
      meta[k] = nil
    end
  end

  return meta
end
