add_newline = false

[directory]
truncation_length = 5
truncation_symbol = "…/"
repo_root_style = "cyan bold italic"
repo_root_format = '[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
read_only = " 󰌾"

[hostname]
# ssh_symbol = ""
ssh_symbol = " "
format = '[$ssh_symbol$hostname:]($style)'

[git_branch]
# symbol = "±"
symbol = " "
style = "green"

[git_status]
format = '([\[](white bold)[$all_status$ahead_behind]($style)[\]](white bold)) '
ahead = "↑"
behind = "↓"
conflicted = "[!](red)"
diverged = "↕"
modified = '[!](bright-yellow bold)'
renamed = '[»](bright-yellow bold)'
staged = '[+](green bold)'
up_to_date = '[≡](green bold)'
windows_starship = "starship.exe"

[status]
disabled = false
# symbol = ''
symbol = '󰗼 '

[shell]
disabled = false
zsh_indicator = ''
powershell_indicator = ''
unknown_indicator = 'sh?'
format = '[$indicator]($style)'

# [battery]
# full_symbol = "🔋 "
# charging_symbol = "⚡️ "
# discharging_symbol = "💀 "
# unknown_symbol = "💀 "
# empty_symbol = "🪫 "
[[battery.display]]
threshold = 10
style = "bold red"
[[battery.display]]
threshold = 30
style = "bold yellow"

[env_var.http_proxy]
format = '󰚻 '

[env_var.WSL_DISTRO_NAME]
format = 'in 🪟 [$env_value]($style) '

[env_var.__MISE_SESSION]
format = '𝔐 '

[gcloud]
disabled = true

# [nodejs]
# symbol = '🤖 '
#
# [erlang]
# symbol = "ⓔ "
#
# [pulumi]
# symbol = "🧊 "

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "
