#!/usr/bin/env bash
#MISE alias="g:up"
#MISE dir="~"
#MISE description="Update all apps"

if command -v apt &>/dev/null; then
    sudo apt update && sudo apt upgrade
fi

if command -v brew &>/dev/null; then
    brew update && brew upgrade
fi

if command -v paru &>/dev/null; then
    paru -Syu
fi

if command -v uv &>/dev/null; then
    mise run g:up:uv
fi

if command -v bun &>/dev/null; then
    mise run g:up:bun
fi
