name: Package Vim files

on:
  push:
    paths: "default/.vimrc"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Package Vim files
        run: |
          mkdir -p vimfiles

          mv default/.vimrc vimfiles/vimrc

          mkdir -p vimfiles/nvim
          mv nvim/{after,macros,pack,package.json,plugin,snippets} vimfiles/nvim/

          mv .github/files/install-vimfiles.py vimfiles/install.py

      - name: Upload Vim files
        uses: actions/upload-artifact@v1
        with:
          name: vimfiles
          path: vimfiles
