#!/usr/bin/env ruby

require "string-utils"

dir = ARGV.shift || "."

files = `gpicker #{StringUtils.shell_escape(dir)}`.split("\0")

cmd = ARGV
cmd = ["emacs-dwim"] if cmd.empty?

exec *(cmd + files)
