#!/bin/bash

VAR_HOST=ian@iany.me
VAR_SESSION_NAME=tunnel
VAR_PORT=9999

stop () {
    screen -S "$VAR_SESSION_NAME" -X quit 2> /dev/null
}

start () {
    screen -S "$VAR_SESSION_NAME" -d -m ssh -D 0.0.0.0:"$VAR_PORT" "$VAR_HOST" 'while true; do date; sleep 60; done'
}

main () {
    local action=start
    if [ -n "$1" ]; then
        action="$1"
    fi

    case "$action" in
    start)
        stop
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo 'unknow action'
        ;;
    esac
}

main "$@"
