#!/bin/bash

[ -z "$1" ] && exit 1
amixer sset Master "$1" > /dev/null || exit 1

AMIXEROUT=$(amixer sget Master)
VOLUME=$(echo "$AMIXEROUT" | sed -n 's/^.*\[\([0-9]*\)%\].*/\1/p;T;q')
[ -z "$VOLUME" ] && VOLUME=0

if echo "$AMIXEROUT" | grep -q '\[off\]' > /dev/null; then
    ICON=notification-audio-volume-muted
else
    if [ $VOLUME -eq 0 ]; then
        ICON=notification-audio-volume-off
    elif [ $VOLUME -lt 33 ]; then
        ICON=notification-audio-volume-low
    elif [ $VOLUME -lt 66 ]; then
        ICON=notification-audio-volume-medium
    else
        ICON=notification-audio-volume-high
    fi
fi

notify-send "Volume" -i $ICON -h int:value:$VOLUME -h string:x-canonical-private-synchronous:true
